# CHANGE host TO localhost if you want to run locally without Docker
# CHANGE username and password to match local postgres db
default: &default
  adapter: postgresql
  encoding: unicode
  host: db      
  username: postgres
  password: <%= ENV['DB_USER_PASSWORD'] %>
  pool: 5

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test